apiVersion: v1
kind: Secret
metadata:
  name: dotnet-monitor-secrets
  namespace: wad2026-diagnostics
type: Opaque
stringData:
  # example secrets from ../scripts/dotnet-monitor-generatedSecret-example.jsonc
  Authentication__MonitorApiKey__PublicKey: >-
    eyJjcnYiOiJQLTM4NCIsImtleV9vcHMiOltdLCJrdHkiOiJFQyIsIm90aCI6W10sIngiOiJhcFVZQVZRWFFQZWpIaGJ6S21WcFFkU0xtZDl0QVliVzhqVm1oVlRkZ3hBSFVIOUxkMVFzdTZWdlMtY2FXbDNiIiwieDVjIjpbXSwieSI6IkFRZXRYcS1mbjhxSktMeENkNGZHUjltM3dEazZCTDNyNmJZR0tkQWc2ODFMMEhRNEgwZjVRS1FYMHpoNXdfU0UifQ
  Authentication__MonitorApiKey__Subject: "82e14544-5f3a-4d3e-a581-7a4a73c7c25d"
  Kestrel__Certificates__Default__Path: "/etc/ssl/certs/dotnet-monitor-tls/keystore.p12" 
  Kestrel__Certificates__Default__Password: "<your-chosen-cert-password>"
