apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-memory-leak
  namespace: wad2026-diagnostics
  labels:
    app: demo-memory-leak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-memory-leak
  template:
    metadata:
      labels:
        app: demo-memory-leak
    spec:
      imagePullSecrets:
        - name: <registry-secrets>

      # Pod-level security defaults
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1654
        runAsGroup: 1654

      containers:
        - name: demo-memory-leak
          image: <your-registy.net>/demo-memory-leak:0.1.0
          imagePullPolicy: IfNotPresent

          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:8080
            - name: DOTNET_DiagnosticPorts
              value: "/diagnosticArtifacts/dotnet-mymonitor.sock,nosuspend"
          volumeMounts:
            - name: artifacts-volume
              mountPath: /diagnosticArtifacts
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

        - name: dotnet-monitor
          image: mcr.microsoft.com/dotnet/monitor:10
          args: ["collect", "--no-auth"]
          imagePullPolicy: Always
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: dotnet-monitor
              containerPort: 52323
          env:
            - name: DOTNETMONITOR_Urls
              value: http://localhost:52323
            - name: DOTNETMONITOR_Storage__DefaultSharedPath
              value: /diagnosticArtifacts
            - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
              value: "listen"
            - name: DOTNETMONITOR_DiagnosticPort__EndpointName
              value: /diagnosticArtifacts/dotnet-mymonitor.sock
          volumeMounts:
            - name: artifacts-volume
              mountPath: /diagnosticArtifacts
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 256Mi

      volumes:
        - name: artifacts-volume
          emptyDir: {}
